spring.application.name=api

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3
game.connectfour.default-player-count=2
game.connectfour.default-board-size=7
game.taquin.default-player-count=1
game.taquin.default-board-size=4
